#!/usr/bin/env python
"""
This file is auto-generated.
Do not edit manually, as changes might get overwritten.
"""
__author__ = r"auto-generated by make/make.py"
__date__ = "2017-02-20T17:30:44"
__package__ = "example"
import sys, os

thisDir = os.path.dirname(__file__)
# File path attributes:
# Vector files:
exampleGPKG = os.path.join(thisDir, r'exampleEvents.gpkg')
exampleEvents = exampleGPKG + '|layername=exampleEvents'
