#!/usr/bin/env python
"""
This file is auto-generated.
Do not edit manually, as changes might get overwritten.
"""
__author__ = r"auto-generated by make/make.py"
__date__ = "2017-02-20T17:30:44"

import sys, os

thisDir = os.path.dirname(__file__)
# File path attributes:
# Vector files:
exampleEvents = os.path.join(thisDir,r'exampleEvents.shp')



# self-test to check each file path attribute
for a in dir(sys.modules[__name__]):
    v = getattr(sys.modules[__name__], a)
    if type(v) == str and os.path.isabs(v):
        if not os.path.exists(v):
            sys.stderr.write('Missing package attribute file: {}={}'.format(a, v))

# cleanup
del thisDir, a, v 