# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: qgis/qgis

pipelines:
  default:
    - step:
        services:
          - docker
        caches:
          - docker
          - pip
          - qgisresourcecache
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get -y install git-lfs
          - mkdir test-reports
          - git lfs install
          - git lfs fetch
          - git lfs pull
          - git lfs checkout
          - QT_QPA_PLATFORM=offscreen
          - CI=True
          - export QT_QPA_PLATFORM
          - export CI
          - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          - python3 -m pip install -r requirements_dev.txt
          - python3 scripts/setup_repository.py
          - python3 -m coverage run --rcfile=.coveragec   tests/test_fileFormatLoading.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_inmemorydata.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_labeling.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_layerproperties.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_main.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_mapcanvas.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_maptools.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_mapvisualization.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_qgis_environment.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_qgis_interaction.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_resources.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_settings.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_stackedbandinput.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_temporalprofiles.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_timeseries.py
          - python3 -m coverage run --rcfile=.coveragec --append  tests/test_utils.py
          - python3 -m coverage report

definitions:
  caches:
    qgisresourcecache: /opt/atlassian/pipelines/agent/build/qgisresources
