#!/usr/bin/env python
"""
This file is auto-generated.
Do not edit manually, as changes might get overwritten.
"""
__author__ = "auto-generated by make/make.py"
__date__ = "2017-07-18T08:44:16+0200"

import sys, os

thisDir = os.path.dirname(__file__)
# File path attributes:
# Raster files:
Img_2014_01_15_LC82270652014015LGN00_BOA = os.path.join(thisDir,r'2014-01-15_LC82270652014015LGN00_BOA.tif')
Img_2014_03_20_LC82270652014079LGN00_BOA = os.path.join(thisDir,r'2014-03-20_LC82270652014079LGN00_BOA.tif')
Img_2014_04_21_LC82270652014111LGN00_BOA = os.path.join(thisDir,r'2014-04-21_LC82270652014111LGN00_BOA.tif')
Img_2014_04_29_LE72270652014119CUB00_BOA = os.path.join(thisDir,r'2014-04-29_LE72270652014119CUB00_BOA.tif')
Img_2014_05_07_LC82270652014127LGN00_BOA = os.path.join(thisDir,r'2014-05-07_LC82270652014127LGN00_BOA.tif')
Img_2014_05_15_LE72270652014135CUB00_BOA = os.path.join(thisDir,r'2014-05-15_LE72270652014135CUB00_BOA.tif')
Img_2014_05_23_LC82270652014143LGN00_BOA = os.path.join(thisDir,r'2014-05-23_LC82270652014143LGN00_BOA.tif')
Img_2014_05_31_LE72270652014151CUB00_BOA = os.path.join(thisDir,r'2014-05-31_LE72270652014151CUB00_BOA.tif')
Img_2014_06_08_LC82270652014159LGN00_BOA = os.path.join(thisDir,r'2014-06-08_LC82270652014159LGN00_BOA.tif')
Img_2014_06_16_LE72270652014167CUB00_BOA = os.path.join(thisDir,r'2014-06-16_LE72270652014167CUB00_BOA.tif')
Img_2014_06_24_LC82270652014175LGN00_BOA = os.path.join(thisDir,r'2014-06-24_LC82270652014175LGN00_BOA.tif')
Img_2014_07_02_LE72270652014183CUB00_BOA = os.path.join(thisDir,r'2014-07-02_LE72270652014183CUB00_BOA.tif')
Img_2014_07_10_LC82270652014191LGN00_BOA = os.path.join(thisDir,r'2014-07-10_LC82270652014191LGN00_BOA.tif')
Img_2014_07_18_LE72270652014199CUB00_BOA = os.path.join(thisDir,r'2014-07-18_LE72270652014199CUB00_BOA.tif')
Img_2014_07_26_LC82270652014207LGN00_BOA = os.path.join(thisDir,r'2014-07-26_LC82270652014207LGN00_BOA.tif')
Img_2014_08_03_LE72270652014215CUB00_BOA = os.path.join(thisDir,r'2014-08-03_LE72270652014215CUB00_BOA.tif')
Img_2014_08_11_LC82270652014223LGN00_BOA = os.path.join(thisDir,r'2014-08-11_LC82270652014223LGN00_BOA.tif')
Img_2014_08_19_LE72270652014231CUB00_BOA = os.path.join(thisDir,r'2014-08-19_LE72270652014231CUB00_BOA.tif')
Img_2014_08_27_LC82270652014239LGN00_BOA = os.path.join(thisDir,r'2014-08-27_LC82270652014239LGN00_BOA.tif')
Img_2014_09_04_LE72270652014247CUB00_BOA = os.path.join(thisDir,r'2014-09-04_LE72270652014247CUB00_BOA.tif')
Img_2014_09_12_LC82270652014255LGN00_BOA = os.path.join(thisDir,r'2014-09-12_LC82270652014255LGN00_BOA.tif')
Img_2014_09_20_LE72270652014263CUB00_BOA = os.path.join(thisDir,r'2014-09-20_LE72270652014263CUB00_BOA.tif')
Img_2014_09_28_LC82270652014271LGN00_BOA = os.path.join(thisDir,r'2014-09-28_LC82270652014271LGN00_BOA.tif')
Img_2014_10_06_LE72270652014279CUB00_BOA = os.path.join(thisDir,r'2014-10-06_LE72270652014279CUB00_BOA.tif')
Img_2014_10_14_LC82270652014287LGN00_BOA = os.path.join(thisDir,r'2014-10-14_LC82270652014287LGN00_BOA.tif')
Img_2014_11_07_LE72270652014311CUB00_BOA = os.path.join(thisDir,r'2014-11-07_LE72270652014311CUB00_BOA.tif')
Img_2014_11_15_LC82270652014319LGN00_BOA = os.path.join(thisDir,r'2014-11-15_LC82270652014319LGN00_BOA.tif')
Img_2014_12_17_LC82270652014351LGN00_BOA = os.path.join(thisDir,r'2014-12-17_LC82270652014351LGN00_BOA.tif')
re_2014_06_25 = os.path.join(thisDir,r're_2014-06-25.tif')
re_2014_08_17 = os.path.join(thisDir,r're_2014-08-17.tif')
re_2014_08_20 = os.path.join(thisDir,r're_2014-08-20.tif')
re_2014_08_26 = os.path.join(thisDir,r're_2014-08-26.tif')



# self-test to check each file path attribute
for a in dir(sys.modules[__name__]):
    v = getattr(sys.modules[__name__], a)
    if type(v) == str and os.path.isabs(v):
        if not os.path.exists(v):
            sys.stderr.write('Missing package attribute file: {}={}'.format(a, v))

# cleanup
del thisDir, a, v 