name: 🧪 Code Testing

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main

  release:
    types: [ published ]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        qgis_version: [ '3.40', '3.42', '3.44' ]
        python: [ '3.12' ]
    env:
      QGIS_VERSION: ${{ matrix.qgis_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - name: Git Status
        run: |
          git status
          git submodule status --recursive
          git lfs status

      - name: Docker Environment Info
        run: |
          docker --version
      - name: Python Packages Info
        run: pip list
      - name: Example Images
        run: |
          ls -lash example/Images
      - name: Test EO Time Series Viewer on QGIS
        run: |
          chmod +x .docker/run_docker_tests.sh
          ls -la .docker/
          docker compose -f .docker/docker-compose.gh.yml run qgis /usr/src/.docker/run_docker_tests.sh
